"""Consumer-input emitters: bundle -> ready-to-edit IRMA inputs.

From a phonon-model bundle plus the nuclear-data table, generate starting
inputs for IRMA's three consumers:

- ENDF decks (one per principal scatterer). Crystalline materials get an
  iel=10 deck with ``inelastic_mode`` 0, 1 or 2 (default 2) and
  ``elastic_format`` mef (default) or sef. Modes 1/2 read the bundle's
  phonopy.yaml (use_born=0: NAC, when present, is embedded in it), with
  explicit automatic grids and Card 6g 10000/1000/auto; mode 2 writes
  lin-lin iint=1, modes 0/1 log-lin iint=0. Mode 0 uses the bundle's
  species-projected DOS: the principal's spectrum on Cards 11-14 and one
  Card 6e partial spectrum per non-principal species. Disordered materials
  get the classic continuous-spectrum deck: the species DOS drives contin,
  and the elastic term is incoherent with SB = sigma_bound_total (the
  incoherent approximation applied to elastic; Card 5 spr is the free-atom
  value, so the writer's SB = sb*npr is the bound total).
- A spectra YAML (scatterers in the bundle's resolved species order; the
  forward model has no principal scatterer).
- An NCrystal exporter YAML (crystalline only).

Config YAMLs are checked with their real config loaders before they are
kept. Nothing executes.

Nuclide identity: a phonopy model names elements, not isotopes, so the
default identity is the natural element (ENDF codes it A = 0) and the
constants are that element's natural-abundance values. Identity and
constants therefore always come from the same table entry. Explicit
--nuclide mappings select an isotope and take both from it. Nuclides the
source table marks energy-dependent are refused as silent prefills.

All heavy imports are function-level (core-clean module).
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass

from irma.mlip.bundle import Bundle

GENERATED_NOTE = ("generated by `irma mlip emit` as a STARTING POINT: review "
                  "every parameter before production use")
_OVERRIDE_KEYS = {"awr", "b_coh_fm", "sigma_inc_b", "sigma_bound_b"}
SAMPLING = (10000, 1000, 1)          # Card 6g: ndir mpdir auto_order
NPHON_CARD3 = 100
MESH_QDEN_PROD = 98.0                # per-axis rule int(98/a_i)+1, see _emit_mesh
MESH_FLOOR = 8


def _emit_ncpu():
    """Card 6f ncpu prefill: the emitting machine's core count (the
    runtime clamps to whatever the executing machine actually has)."""
    return os.cpu_count() or 1


def _emit_mesh(bundle):
    """Mesh prefilled into every emitted input: production density.

    int(MESH_QDEN_PROD/a_i)+1 per axis, a uniform reciprocal-space
    density: on graphite it gives 40 along a and b (a = 2.461 A), the
    in-plane density of the 40x40x40 validation mesh, and 15 along c
    (6.71 A). The build's --mesh sets only the bundle's quick-look DOS and
    census mesh, not this one. Disordered bundles keep their Gamma-only
    mesh (the classic DOS path never sums over q).
    """
    if bundle.manifest.get("disordered"):
        return [int(n) for n in bundle.manifest["phonons"]["mesh"]]
    return [max(MESH_FLOOR, int(MESH_QDEN_PROD / float(a)) + 1)
            for a in _cellpar(bundle)[:3]]


@dataclass
class Species:
    symbol: str
    Z: int
    A: int                    # the ZA identity (0 = natural element)
    awr: float                # natural or override
    b_coh_fm: float
    sigma_inc_b: float
    sigma_bound_b: float
    positions: list           # fractional, from the relaxed structure
    identity_source: str      # "explicit" | "natural"
    constants_source: str     # "table" | "override"

    @property
    def za(self) -> int:
        return 1000 * self.Z + self.A

    @property
    def sigma_free_b(self) -> float:
        return self.sigma_bound_b * (self.awr / (self.awr + 1.0)) ** 2


# --------------------------------------------------------------- species ----

def resolve_species(bundle: Bundle, *, nuclides=None, overrides=None,
                    progress=print) -> list:
    """Species list from the relaxed structure + nuclear-data table.

    nuclides: {symbol: nuclide-label} explicit ZA identities.
    overrides: {symbol: {field: value}} scattering-constant overrides
               (fields: awr, b_coh_fm, sigma_inc_b, sigma_bound_b).
    """
    from ase.io import read as ase_read
    from irma.core.nuclear_data import lookup

    nuclides = dict(nuclides or {})
    overrides = dict(overrides or {})
    atoms = ase_read(bundle.structure)
    spos = atoms.get_scaled_positions()

    order, positions = [], {}
    for symbol, pos in zip(atoms.get_chemical_symbols(), spos):
        if symbol not in positions:
            order.append(symbol)
            positions[symbol] = []
        positions[symbol].append(tuple(float(x) for x in pos))

    for what, mapping in (("--nuclide", nuclides), ("--species", overrides)):
        unknown = sorted(set(mapping) - set(order))
        if unknown:
            raise ValueError(f"{what} names species not present in the "
                             f"structure: {unknown} (present: {order})")
    for symbol, ov in overrides.items():
        bad = sorted(set(ov) - _OVERRIDE_KEYS)
        if bad:
            raise ValueError(
                f"--species {symbol}: unknown field(s) {bad}; allowed: "
                f"{sorted(_OVERRIDE_KEYS)}")

    species = []
    for symbol in order:
        if symbol in nuclides:
            # Explicit nuclide: both the ZA identity and the base constants
            # come from the isotope entry.
            base = lookup(nuclides[symbol])
            if base.symbol != symbol:
                raise ValueError(
                    f"--nuclide maps {symbol} to {nuclides[symbol]} "
                    f"({base.symbol}); the nuclide must be an isotope of the "
                    f"same element")
            z, a = base.Z, base.A
            identity = "explicit"
        else:
            # A phonopy model names an element, not an isotope, so the
            # default is the natural element: ENDF codes it A = 0, and the
            # constants below come from the same entry, so the identity and
            # the constants agree.
            base = lookup(symbol)          # natural-element constants
            z, a = base.Z, 0
            identity = "natural"
            progress(f"  {symbol}: natural element (za={1000 * z}); "
                     f"select an isotope with --nuclide {symbol}=<A>-{symbol} "
                     f"to take its identity and its constants")

        ov = overrides.get(symbol, {})
        # An energy-dependent tabulated length is accepted only when the
        # user supplies both scattering constants; an awr-only or mistyped
        # override does not let the flagged values through.
        if base.energy_dependent and not {"b_coh_fm",
                                          "sigma_inc_b"} <= set(ov):
            raise ValueError(
                f"{symbol}: the tabulated scattering length is marked "
                f"ENERGY-DEPENDENT (resonance-region value) and is not a "
                f"safe prefill; supply explicit b_coh_fm and sigma_inc_b "
                f"via --species {symbol}:...")
        awr = float(ov.get("awr", base.awr))
        b_coh = float(ov.get("b_coh_fm", base.b_coh_fm))
        sigma_inc = float(ov.get("sigma_inc_b", base.sigma_inc_b))
        # sigma_bound is always derived from (b_coh, sigma_inc): the triple
        # must stay self-consistent because mode-2 renormalizes from the
        # Card 6d constants (driver.py). A supplied value is only accepted
        # as a cross-check within 0.5%.
        sigma_bound = 0.04 * 3.141592653589793 * b_coh * b_coh + sigma_inc
        if "sigma_bound_b" in ov:
            supplied = float(ov["sigma_bound_b"])
            if abs(supplied - sigma_bound) > 0.005 * max(sigma_bound, 1e-12):
                raise ValueError(
                    f"--species {symbol}: sigma_bound_b={supplied:g} is "
                    f"inconsistent with 4*pi*b_coh^2/100+sigma_inc="
                    f"{sigma_bound:g} (the deck derives coherent quantities "
                    f"from b_coh, so an independent bound value would make "
                    f"the tape contradict itself); adjust b_coh_fm/"
                    f"sigma_inc_b instead")
        species.append(Species(
            symbol=symbol, Z=z, A=a, awr=awr, b_coh_fm=b_coh,
            sigma_inc_b=sigma_inc, sigma_bound_b=sigma_bound,
            positions=positions[symbol],
            identity_source=identity,
            constants_source="override" if ov else "table"))
    return species


# ----------------------------------------------------------------- grids ----

def _auto_grids(freq_max_ev, awr, temperature_k, iint, coarse=None):
    """The shared automatic grids; `coarse` (test/preview use) shrinks them
    by scaling the density knobs while keeping the same construction."""
    from irma.core.grids import (
        AUTO_GRID_DEFAULTS, describe_beta_grid, generate_alpha_grid,
        generate_beta_grid, grid_reference_temperature_K)
    d = dict(AUTO_GRID_DEFAULTS)
    if coarse:
        d["n_lower"], d["n_phonon"], d["n_upper"] = 10, 40, 10
        d["alpha_dq_invA"], d["alpha_nlog"] = 0.5, 20
    tref = grid_reference_temperature_K(1, float(temperature_k))
    beta = generate_beta_grid(
        float(freq_max_ev), tref, iint=iint, awr=float(awr),
        n_lower=d["n_lower"], n_phonon=d["n_phonon"],
        n_upper=d["n_upper"], beta_max_eV=d["beta_max_eV"],
        evaluation_temperatures_K=[float(temperature_k)])
    alpha = generate_alpha_grid(
        beta, float(awr), tref, dq_ang_inv=d["alpha_dq_invA"],
        q_cut_ang_inv=d["alpha_qcut_invA"], n_log=d["alpha_nlog"])
    if not coarse:
        print("  " + describe_beta_grid(beta, tref, iint), flush=True)
    return alpha, beta


def _array_lines(values, ncols=5):
    lines = []
    for i in range(0, len(values), ncols):
        chunk = values[i:i + ncols]
        tail = " /" if i + ncols >= len(values) else ""
        lines.append(" ".join(f"{float(x):.6e}" for x in chunk) + tail)
    return lines


# ------------------------------------------------------------- ENDF decks ----

def _guard_target(path, overwrite):
    if os.path.exists(path) and not overwrite:
        raise FileExistsError(
            f"{path} exists; pass overwrite=True (--overwrite) to replace it")


def emit_endf_decks(bundle: Bundle, *, temperature_k, mats, nuclides=None,
                    overrides=None, out_dir=None, overwrite=False,
                    allow_unstable=False, inelastic_mode=None,
                    elastic_format="mef", min_phonon_energy_mev=0.0,
                    _preview=False, progress=print) -> list:
    """One deck per principal scatterer; layout depends on disordered.

    ``inelastic_mode`` selects the emitted deck's physics level (0, 1, or
    2; default 2). Mode 0 is the classic isotropic path driven by the
    bundle's species-projected DOS: the principal's spectrum goes on the
    classic cards and every other species gets a Card 6e partial spectrum,
    so each species' elastic W'(T) uses its own lambda. Modes 1/2 are the
    phonopy-backed decks (per-species Debye-Waller from the displacement
    tensors; no Card 6e). Mode 2 writes lin-lin (iint=1); modes 0/1 keep
    the log-lin default (iint=0). ``elastic_format`` is ``"mef"`` (default:
    both elastic components on every species' tape) or ``"sef"``. Both
    options are crystal-deck selectors: a disordered bundle (classic
    DOS-driven deck, no Card 6b) rejects them.
    """
    species = resolve_species(bundle, nuclides=nuclides, overrides=overrides,
                              progress=progress)
    known = {s.symbol for s in species}
    extra = sorted(set(mats or {}) - known)
    if extra:
        raise ValueError(f"--mat names species not present in the "
                         f"structure: {extra} (present: {sorted(known)})")
    missing = [s.symbol for s in species if s.symbol not in (mats or {})]
    if missing:
        raise ValueError(
            f"MAT numbers are required for ENDF emission (one per principal "
            f"scatterer): missing {missing}; pass --mat "
            + " ".join(f"'{s}=<mat>'" for s in missing))
    for symbol, mat in mats.items():
        if isinstance(mat, bool) or not isinstance(mat, int) or mat < 1:
            raise ValueError(f"--mat {symbol}={mat!r}: MAT must be an "
                             f"integer >= 1")
    if not temperature_k > 0:
        raise ValueError(f"--temperature must be > 0, got {temperature_k!r}")

    disordered = bool(bundle.manifest.get("disordered"))
    if float(min_phonon_energy_mev) > 0.0 and (disordered or inelastic_mode == 0):
        raise ValueError(
            "--min-phonon-energy applies to the phonopy-backed decks "
            "(--inelastic-mode 1 or 2) only; the DOS-driven "
            + ("classic deck of a disordered bundle" if disordered else "mode-0 deck")
            + " does not use it")
    out_dir = out_dir or bundle.path
    os.makedirs(out_dir, exist_ok=True)
    if disordered:
        if inelastic_mode is not None:
            raise ValueError(
                "disordered bundles use the DOS-driven classic path and "
                "ignore the crystal deck layouts; --inelastic-mode is not "
                "applicable there")
        if elastic_format != "mef":
            raise ValueError(
                "disordered bundles use the DOS-driven classic path, whose "
                "elastic term is always the incoherent format (no Card 6b); "
                "--elastic-format is not applicable there")
        return _emit_classic_decks(bundle, species, temperature_k, mats,
                                   out_dir, progress,
                                   allow_unstable=allow_unstable,
                                   overwrite=overwrite)
    return _emit_iel10_decks(bundle, species, temperature_k, mats,
                             out_dir, progress, overwrite=overwrite,
                             inelastic_mode=(2 if inelastic_mode is None
                                             else inelastic_mode),
                             min_phonon_energy_mev=min_phonon_energy_mev,
                             elastic_format=elastic_format,
                             allow_unstable=allow_unstable,
                             _preview=_preview)


def _qpath(path) -> str:
    """Quote a filesystem path for a deck string card (apostrophes doubled)."""
    return "'" + str(path).replace("'", "''") + "'"


def _cellpar(bundle):
    from ase.io import read as ase_read
    atoms = ase_read(bundle.structure)
    return [float(x) for x in atoms.cell.cellpar()]


def _header_comment(bundle, extra=""):
    text = (f"{GENERATED_NOTE}; bundle {bundle.path}; "
            f"fingerprint {bundle.fingerprint[:16]}{extra}")
    return text.replace("'", "''")     # '-safe (emitted YAML header lines)


_MONTHS = ("JAN", "FEB", "MAR", "APR", "MAY", "JUN",
           "JUL", "AUG", "SEP", "OCT", "NOV", "DEC")


def _comment_cards(bundle, symbol, extra=""):
    """MF1/MT451 comment cards for an emitted deck.

    The ENDF writer maps card 1 onto the fixed-column header
    (ZSYMAM/ALAB/EDATE/AUTH, cut at column 66), card 2 onto
    REF/DDATE/RDATE/ENDATE, cards 3-5 onto HSUB1-3, and later cards onto
    DESCRIPTION records. A long provenance line on card 1 would be cut at
    column 66, so card 1 is a short header on those columns, cards 2-5 are
    left blank for the user, and the provenance (bundle path, fingerprint)
    goes on DESCRIPTION cards of at most 66 columns.
    """
    import datetime
    import textwrap
    today = datetime.date.today()
    zsymam = f" {symbol}-MLIP"[:11].ljust(11)
    alab = "IRMA".ljust(11)
    edate = f"EVAL-{_MONTHS[today.month - 1]}{today.year % 100:02d}"
    card1 = f"{zsymam}{alab}{edate} irma mlip emit"
    cards = [f"'{card1}' /"]
    cards += ["' ' /"] * 4                    # REF/DDATE + HSUB1-3 slots
    provenance = (f"{GENERATED_NOTE}; bundle {bundle.path}; "
                  f"fingerprint {bundle.fingerprint[:16]}{extra}")
    for line in textwrap.wrap(provenance, width=65):
        # column-1 blank by convention; apostrophes doubled after wrapping
        # (the tokenizer folds '' back to ', so the 66-column budget is the
        # undoubled length)
        cards.append("' " + line.replace("'", "''") + "' /")
    return cards


def _write_deck(path, lines, overwrite):
    _guard_target(path, overwrite)
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def _uniform_rho(e_mev, rho):
    """Resample a projected DOS onto the uniform grid the deck cards take.

    Returns ``(delta_ev, ni, rho_uni)`` on bundle.dos_grid_mev, so a
    species DOS from _species_dos is not resampled; rho(0) is pinned to 0.
    """
    import numpy as np
    from irma.mlip.bundle import dos_grid_mev
    e_uni = dos_grid_mev(e_mev.max())
    ni = len(e_uni)
    rho_uni = np.interp(e_uni, e_mev, rho)
    rho_uni[0] = 0.0
    delta_ev = float(e_uni[1] - e_uni[0]) * 1e-3
    return delta_ev, ni, rho_uni


def _emit_iel10_decks(bundle, species, temperature_k, mats, out_dir,
                      progress, overwrite=False, inelastic_mode=2,
                      min_phonon_energy_mev=0.0,
                      elastic_format="mef", allow_unstable=False,
                      _preview=False):
    """_preview (tests/smoke only): coarse grids + tiny sampling + low
    phonon order, so an emitted deck can be run through the engine in
    seconds. Never a production surface."""
    freq_max_ev = bundle.manifest["phonons"]["freq_max_meV"] * 1e-3
    mesh = _emit_mesh(bundle)
    cellpar = _cellpar(bundle)
    nat = len(species)
    ef_field = 2 if elastic_format == "mef" else 1
    sampling = (50, 20, 1) if _preview else SAMPLING
    nphon = 2 if _preview else NPHON_CARD3
    # mode 2 keeps lin-lin (INT=2: sharp coherent structure); the
    # incoherent-approximation modes 0/1 are smooth and keep the log-lin
    # default, matching the validation campaign's tape conventions.
    iint = 1 if inelastic_mode == 2 else 0
    dos = None
    if inelastic_mode == 0:
        _require_stable(bundle, allow_unstable)
        dos = _species_dos(bundle, species, progress)
    paths = []
    for prin in species:
        alpha, beta = _auto_grids(freq_max_ev, prin.awr, temperature_k,
                                  iint=iint, coarse=_preview)
        others = ([s for s in species if s is not prin]
                  if inelastic_mode == 0 else [])
        lines = [
            "20 /",
            f"'tsl {prin.symbol} in MLIP model | {GENERATED_NOTE}' /",
            f"1 1 {nphon} /",
            f"{mats[prin.symbol]} {prin.za} 0 0 1.000000e-75 {iint} /",
            f"{prin.awr:.6f} {prin.sigma_free_b:.9f} 1 10 0 0 /",
            "0 0 0 0 0 /",
            f"{ef_field} {nat} {len(others)} {inelastic_mode} /",
            " ".join(f"{v:.6f}" for v in cellpar) + " /",
        ]
        for s in species:            # every Card 6d group on every deck
            lines.append(f"{s.Z} {s.A} {s.awr:.6f} {s.b_coh_fm:.6f} "
                         f"{s.sigma_inc_b:.6f} {len(s.positions)} /")
            coords = "  ".join(
                f"{x:.6f} {y:.6f} {z:.6f}" for x, y, z in s.positions)
            lines.append(f"{coords} /")
        if inelastic_mode in (1, 2):
            lines += [
                f"{_qpath(bundle.phonopy_yaml)} /",
                f"{mesh[0]} {mesh[1]} {mesh[2]} "
                f"{2 if _preview else _emit_ncpu()} 0 /",
            ]
            if float(min_phonon_energy_mev) > 0.0:
                # the optional one-value card before Card 6g
                lines.append(f"{float(min_phonon_energy_mev):g} /")
            lines.append(f"{sampling[0]} {sampling[1]} {sampling[2]} /")
        else:
            # Card 6e: every non-principal species' own spectrum, so its
            # elastic W'(T) uses its own lambda (no inherited-lambda
            # fallback on a polyatomic mode-0 deck).
            for s in others:
                delta_ev, ni, rho_uni = _uniform_rho(*dos[s.symbol])
                lines.append(f"{s.Z} {s.A} {delta_ev:.6e} {ni} /")
                lines += _array_lines(rho_uni)
        lines += [
            f"{len(alpha)} {len(beta)} 1 /",
            *_array_lines(alpha),
            *_array_lines(beta),
            f"{float(temperature_k)} /",
        ]
        if inelastic_mode == 0:
            delta_ev, ni, rho_uni = _uniform_rho(*dos[prin.symbol])
            lines += [
                f"{delta_ev:.6e} {ni} /",
                *_array_lines(rho_uni),
                "0.0 0.0 1.0 /",          # twt c tbeta: no translational
                "0 /",                    # no discrete oscillators
            ]
        lines += [
            *_comment_cards(bundle, prin.symbol),
            "/",
        ]
        path = os.path.join(out_dir, f"endf_{prin.symbol}.input")
        _write_deck(path, lines, overwrite)
        progress(f"  wrote {path} (iel=10 mode-{inelastic_mode} "
                 f"{elastic_format.upper()}, za={prin.za}, "
                 f"grid {len(alpha)}x{len(beta)})")
        paths.append(path)
    _write_emit_manifest(bundle, species, mats, out_dir,
                         kind="endf-iel10", overwrite=overwrite,
                         extra={"inelastic_mode": inelastic_mode,
                                "elastic_format": elastic_format})
    return paths


def _species_dos(bundle, species, progress):
    """Species-projected DOS (meV) from the bundle's embedded-FC model: the
    engine's per-atom histogram DOS (``compute_atom_dos``) summed over each
    species' sites, 3 states per atom as phonopy normalizes it."""
    from irma.core.phonopy_io import compute_atom_dos, load_phonopy_mesh
    from irma.mlip.bundle import dos_grid_mev

    mesh = _emit_mesh(bundle)
    progress(f"  computing species-projected DOS on the {tuple(mesh)} mesh")
    # load_phonopy_mesh refuses code-executing YAML tags, runs phonopy in an
    # empty directory (no stray BORN) and pins the primitive matrix
    md = load_phonopy_mesh(bundle.phonopy_yaml, mesh)
    e_mev = dos_grid_mev(float(md.frequencies_ev.max()) * 1.0e3)
    g, _ = compute_atom_dos(md, e_mev[-1] * 1.0e-3, len(e_mev))   # 1/eV, 1 per atom
    out = {}
    for sp in species:
        rows = [i for i, s in enumerate(md.atom_symbols) if s == sp.symbol]
        out[sp.symbol] = (e_mev, 3.0e-3 * g[rows].sum(axis=0))
    return out


def _require_stable(bundle, allow_unstable):
    n_imag = int(bundle.manifest["phonons"].get("n_imaginary", 0))
    if n_imag and not allow_unstable:
        raise ValueError(
            f"the bundle records {n_imag} imaginary mode(s); a DOS-driven "
            f"input from an unstable model silently drops those modes and "
            f"looks deceptively healthy -- fix the model (tighter --fmax, "
            f"larger --supercell, different potential) or pass "
            f"allow_unstable=True (--allow-unstable) to proceed anyway")


def _emit_classic_decks(bundle, species, temperature_k, mats, out_dir,
                        progress, allow_unstable=False, overwrite=False):
    """Disordered: classic continuous-spectrum deck per principal.

    DOS -> contin inelastic; elastic = incoherent-format with
    SB = sigma_bound_total, obtained through Card 5 spr (free-atom
    equivalent, npr=1) and iel=0 + twt=0 (the driver's LTHR=2 route).
    """
    _require_stable(bundle, allow_unstable)
    dos = _species_dos(bundle, species, progress)
    freq_max_ev = bundle.manifest["phonons"]["freq_max_meV"] * 1e-3
    paths = []
    for prin in species:
        delta_ev, ni, rho_uni = _uniform_rho(*dos[prin.symbol])

        alpha, beta = _auto_grids(freq_max_ev, prin.awr, temperature_k,
                                  iint=0)
        sigma_free = prin.sigma_free_b   # writer: SB = sb*npr = bound total
        lines = [
            "20 /",
            f"'tsl {prin.symbol} in disordered MLIP model | incoherent "
            f"elastic SB=sigma_bound_total' /",
            f"1 1 {NPHON_CARD3} /",
            f"{mats[prin.symbol]} {prin.za} 0 0 1.000000e-75 0 /",
            f"{prin.awr:.6f} {sigma_free:.9f} 1 0 0 0 /",
            "0 0 0 0 0 /",
            f"{len(alpha)} {len(beta)} 1 /",
            *_array_lines(alpha),
            *_array_lines(beta),
            f"{float(temperature_k)} /",
            f"{delta_ev:.6e} {ni} /",
            *_array_lines(rho_uni),
            "0.0 0.0 1.0 /",          # twt c tbeta: no translational
            "0 /",                    # no discrete oscillators
            *_comment_cards(bundle, prin.symbol,
                            extra="; disordered classic path"),
            "/",
        ]
        path = os.path.join(out_dir, f"endf_{prin.symbol}.input")
        _write_deck(path, lines, overwrite)
        progress(f"  wrote {path} (classic DOS deck, za={prin.za})")
        paths.append(path)
    _write_emit_manifest(bundle, species, mats, out_dir,
                         kind="endf-classic", overwrite=overwrite)
    return paths


# ------------------------------------------------------------ config YAMLs ----

def _scatterer_entry(s: Species) -> dict:
    return {"symbol": s.symbol, "sigma_bound_b": s.sigma_bound_b,
            "awr": s.awr, "b_coh_fm": s.b_coh_fm,
            "sigma_inc_b": s.sigma_inc_b}


def _dump_yaml_with_header(cfg, out_path, header_lines):
    import yaml
    with open(out_path, "w") as fh:
        for line in header_lines:
            fh.write(f"# {line}\n")
        yaml.safe_dump(cfg, fh, sort_keys=False)


def _grid_section(bundle):
    e_max = 25.0 * (1 + int(bundle.manifest["phonons"]["freq_max_meV"] / 25.0))
    return {"e_min_meV": 0.0, "e_max_meV": float(e_max), "de_meV": 1.0,
            "dq_max_invA": 0.1}


def emit_spectra_yaml(bundle: Bundle, *, temperature_k,
                      nuclides=None, overrides=None, out_path=None,
                      overwrite=False, allow_unstable=False,
                      min_phonon_energy_mev=0.0, progress=print):
    """Spectra config in the real SpectraConfig schema (no unknown keys).

    Scatterers are emitted in the bundle's resolved species order. Unlike
    the ENDF and NCrystal targets there is no principal scatterer here: the
    forward model evaluates every scatterer in one pass, so the list order
    carries no physics. Crystalline bundles get the mode-2 eigenvector
    path; disordered bundles get mode-0 with species-projected DOS files
    and the incoherent-total elastic convention (sigma_inc_b set to the
    TOTAL bound cross section, the incoherent approximation applied to
    elastic -- the same treatment as the emitted classic ENDF deck).
    """
    species = resolve_species(bundle, nuclides=nuclides, overrides=overrides,
                              progress=progress)

    disordered = bool(bundle.manifest.get("disordered"))
    if disordered and float(min_phonon_energy_mev) > 0.0:
        raise ValueError(
            "--min-phonon-energy applies to the phonopy-backed spectra config "
            "of a crystalline bundle only; the mode-0 config of a disordered "
            "bundle does not use it")
    out_path = out_path or os.path.join(bundle.path, "spectra.yaml")
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _guard_target(out_path, overwrite)
    header = [_header_comment(bundle),
              "review grid/instrument before production"]

    if not disordered:
        cfg = {
            "material": {
                "phonopy_yaml": bundle.phonopy_yaml,
                "mesh": _emit_mesh(bundle),
                "temperature_K": float(temperature_k),
                "scatterers": [_scatterer_entry(s) for s in species],
            },
            "physics": {
                "inelastic_mode": 2,
                "max_phonon_order": "auto",
                "min_phonon_energy_meV": float(min_phonon_energy_mev),
                "n_directions": SAMPLING[0],
                "multiphonon_directions": SAMPLING[1],
                "elastic": True,
                "elastic_kind": "both",
            },
            "grid": _grid_section(bundle),
            "instrument": {"geometry": "vision", "e_fixed_meV": 3.5},
        }
    else:
        _require_stable(bundle, allow_unstable)
        # absolute dos paths (matching the crystalline branch's abspathed
        # phonopy_yaml), so the YAML resolves from any working directory
        dos_dir = os.path.dirname(os.path.abspath(out_path))
        dos = _species_dos(bundle, species, progress)
        import numpy as np
        scatterers = []
        for s in species:
            e, rho = dos[s.symbol]
            dpath = os.path.join(dos_dir, f"dos_{s.symbol}.dat")
            _guard_target(dpath, overwrite)
            np.savetxt(dpath, np.column_stack((e, rho)),
                       header="energy_meV dos (species-projected, "
                              "quick-look mesh)")
            entry = _scatterer_entry(s)
            # incoherent-total elastic convention (disordered): the elastic
            # line carries the TOTAL bound cross section
            entry["sigma_inc_b"] = s.sigma_bound_b
            entry["dos_file"] = dpath
            entry["dos_unit"] = "meV"
            entry["multiplicity"] = len(s.positions)
            scatterers.append(entry)
        header.append("disordered: mode-0 DOS path; sigma_inc_b carries the "
                      "TOTAL bound cross section (incoherent approximation "
                      "applied to elastic)")
        cfg = {
            "material": {
                "temperature_K": float(temperature_k),
                "scatterers": scatterers,
            },
            "physics": {
                "inelastic_mode": 0,
                "dos_source": "file",
                "elastic": True,
                "elastic_kind": "incoherent",
            },
            "grid": _grid_section(bundle),
            "instrument": {"geometry": "vision", "e_fixed_meV": 3.5},
        }

    # gate on the .tmp sibling through the REAL validating loader, then swap
    tmp = out_path + ".tmp"
    _dump_yaml_with_header(cfg, tmp, header)
    try:
        from irma.spectra.config import load as spectra_load
        spectra_load(tmp, validate_cfg=True)
    except BaseException:
        os.remove(tmp)
        raise
    os.replace(tmp, out_path)
    progress(f"  wrote {out_path}")
    return out_path


def emit_ncrystal_yaml(bundle: Bundle, *, temperature_k, material_id=None,
                       nuclides=None, overrides=None, out_path=None,
                       overwrite=False, min_phonon_energy_mev=0.0,
                       progress=print):
    """NCrystal exporter config (real NCrystalExportConfig schema).

    Crystalline materials only: IRMA has no coherent-elastic model for
    amorphous matter.
    """
    if bundle.manifest.get("disordered"):
        raise ValueError(
            "NCrystal export is not available for disordered materials: it "
            "needs a coherent-elastic S(Q) model for amorphous matter, which "
            "IRMA does not provide; emit endf or spectra instead")
    species = resolve_species(bundle, nuclides=nuclides, overrides=overrides,
                              progress=progress)
    cfg = {
        "material": {
            "phonopy_yaml": bundle.phonopy_yaml,
            "mesh": _emit_mesh(bundle),
            "temperature_K": float(temperature_k),
            "scatterers": [_scatterer_entry(s) for s in species],
        },
        "export": {
            "material_id": material_id or "mlip_model",
            "inelastic_mode": 2,
            "num_directions": SAMPLING[0],
            "multiphonon_num_directions": SAMPLING[1],
            "multiphonon_max_order": "auto",
            "min_phonon_energy_meV": float(min_phonon_energy_mev),
            "gain_side": "scaled_sym",
            "elastic": True,
            "coherent_partition_mode": "auto",
        },
    }
    out_path = out_path or os.path.join(bundle.path, "ncrystal.yaml")
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _guard_target(out_path, overwrite)
    tmp = out_path + ".tmp"
    _dump_yaml_with_header(cfg, tmp, [_header_comment(bundle)])
    try:
        from irma.ncrystal.config import NCrystalExportConfig
        NCrystalExportConfig.from_yaml(tmp)
    except BaseException:
        os.remove(tmp)
        raise
    os.replace(tmp, out_path)
    progress(f"  wrote {out_path}")
    return out_path


# ------------------------------------------------------------- provenance ----

def _write_emit_manifest(bundle, species, mats, out_dir, kind,
                         overwrite=False, extra=None):
    record = {
        "kind": kind,
        **(extra or {}),
        "bundle": bundle.path,
        "fingerprint": bundle.fingerprint,
        "species": [
            {"symbol": s.symbol, "za": s.za, "mat": mats.get(s.symbol),
             "identity_source": s.identity_source,
             "constants_source": s.constants_source,
             "awr": s.awr, "b_coh_fm": s.b_coh_fm,
             "sigma_inc_b": s.sigma_inc_b, "sigma_bound_b": s.sigma_bound_b}
            for s in species
        ],
    }
    path = os.path.join(out_dir, "emit_manifest.json")
    _guard_target(path, overwrite)
    tmp = path + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(record, fh, indent=2, sort_keys=True)
        fh.write("\n")
    os.replace(tmp, path)
